### ISSUE TITLE
Client-side CORS Issues

### ISSUE THREAD

**Issue by evancloutier** [ynab/ynab-sdk-js#31]
Hi there!

I started to write a basic Vue app using this SDK. Here is a basic Vuex action:

```javascript
import YnabAPI from 'ynab';
import { YNAB_ACCESS_KEY } from '../../config';

const ynab = new YnabAPI(YNAB_ACCESS_KEY);

export const budgets = async () => {
  await ynab.budgets.getBudgets();
};
```

When executing this in Chrome, I'm running into some issues with cross origin requests.

`Failed to load https://api.youneedabudget.com/v1/budgets: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 401. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

Looking in Chrome DevTools, the request is coming back as 401 Unauthorized.

Correct me if I'm wrong, but is this a client-side Javascript library? If so, it appears there are some issues with how these requests are being handled. If not, I think that should be clarified in the README.

I executed a similar action when running `node` in my Terminal, and the request had no problem executing.

Let me know what you think!

**Comment by bradymholt** [comment]
:wave: @evancloutier - thanks for you interest and usage of the YNAB API!  We don't have CORS configured yet so this client will only work from non-browser (i.e. Node) context for now.  It's on our list, though - stay tuned!

**Comment by bradymholt** [comment]
@evancloutier CORS is now supported!  See the main README for browser usage information: https://github.com/ynab/ynab-sdk-js

**Comment by thecooper** [comment]
@bradymholt I don't know if the API has been updated so that browsers can make requests, but I'm having trouble making the call and getting a 401 still even when using the method you describe above. When I use the global `ynab` object and try to make the request to update a monthy category (PATCH), I get the following error: `No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.` I'm not entirely sure what that means but I would have thought that the SDk would have taken care of that for me. Any thoughts on how I can proceed?

**Comment by bradymholt** [comment]
@thecooper - Can you post a an example of the code you are using to make the request?  Also, which browser and version are you using?
