### ISSUE TITLE
getCurrentDateInISOFormat uses system time, not UTC

### ISSUE THREAD

**Issue by lukemgriffith** [ynab/ynab-sdk-js#40]
As the API expects UTC, should it do this? - causing below error when my clock went past midnight in BST.

```
{ error: 
   { id: '400',
     name: 'bad_request',
     detail: '{"transactions":[{"index":0,"error":{"date":["must not be in the future or over 5 years ago"]}}]}' } }
```

**Comment by bradymholt** [comment]
Yes, server expects UTC and prevents future UTC date.  This is a bit tricky since most of the time a user would want a transaction dated according to their own timezone date.  But, since we don't allow future dates you end up with situations like this.  Rather than changing this utility to UTC or adding an additional utility for UTC dates, I think a decent solution here would be to allow a future date in the API.  The API doesn't support creating scheduled transactions but technically a transaction with a future date can be created.  I'll work on making a change to the API to accommodate  this.  In the meantime, you'll just need to make sure the data you pass is not greater than UTC.

Thanks for letting us know about this.

**Comment by bradymholt** [comment]
@lukemgriffith Thanks for letting us know about this.  There is an issue on the API itself that is causing this.  We should be allowing a date 1 day in the future but we are incorrectly comparing the date/time passed in with the current UTC date and the time portion is throwing off the comparison.  I'll get a fix in!
