### ISSUE TITLE
UpdateTransaction.id type should allow for null value

### ISSUE THREAD

**Issue by cassus** [ynab/ynab-sdk-js#97]
> Each transaction must have either an ‘id’ or ‘import_id’ specified. **If ‘id’ is specified as null** an ‘import_id’ value can be provided which will allow transaction(s) to be updated by their import_id. If an id is specified, it will always be used for lookup.
> 
> From https://api.youneedabudget.com/v1#/Transactions/updateTransactions

**Comment by bradymholt** [comment]
@cassus - I am almost certain Swagger 2.0 does not support nullable types.  When we upgrade to OpenAPI 3 we could specify a nullable type.  I'm going to preemptively close because I don't think there is anything we can do about this on the spec itself . Are you having a problem with a generator?  If so, you may be able to tweak a template or setting on the generator to get what you want.

**Comment by cassus** [comment]
Okay, the workaround is easy, I just use `id: (null as any)`
